name: macOS Build

on:
  workflow_dispatch:

jobs:
  build-macos-arm:
    name: Build macOS ARM
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install Dependencies
        run: |
          python -m pip install .[dev]

      - name: Build ARM executable
        run: |
          pyinstaller macos-arm.spec
          VERSION=$(make print-version)
          cd dist/macos-arm
          cp ../../resources/VFMC-Readme.txt .
          zip -q VFMC-v${VERSION}-Mac-ARM.zip -r VFMC-Readme.txt vfmc.app

      - name: Upload ARM build artifact
        uses: actions/upload-artifact@v4
        with:
          name: VFMC-macOS-ARM
          path: dist/macos-arm/*.zip

  build-macos-x86:
    name: Build macOS X86
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          arch -x86_64 python -m pip install .[dev]

      - name: Build X86 executable
        run: |
          arch -x86_64 pyinstaller macos-x86.spec
          VERSION=$(make print-version)
          cd dist/macos-x86
          cp ../../resources/VFMC-Readme.txt .
          zip -q VFMC-v${VERSION}-Mac-X86.zip -r VFMC-Readme.txt vfmc.app

      - name: Upload ARM build artifact
        uses: actions/upload-artifact@v4
        with:
          name: VFMC-macOS-X86
          path: dist/macos-x86/*.zip

