name: Linux Build

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev

      - name: Install Python dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -e .
          
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "rust-src -> target"

      - name: Build Rust component
        run: |
          source .venv/bin/activate
          cd rust-src
          RUSTFLAGS="-C target-feature=+avx2" maturin develop --release --target x86_64-unknown-linux-gnu
          
      - name: Build Linux executable
        run: |
          source .venv/bin/activate
          pyinstaller linux-x86.spec
          
      - name: Create distribution package
        run: |
          source .venv/bin/activate
          cd dist/linux-x86
          VERSION=$(python -c "from importlib.metadata import version; print(version('vfmc'))")
          tar -czvf VFMC-v$VERSION-Linux.tar.gz VFMC
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VFMC-Linux
          path: dist/linux-x86/*.tar.gz
          
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/linux-x86/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}