name: Linux Build

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev

      - name: Install Python dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -e .
          
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "rust-src -> target"

      - name: Build Rust component
        run: |
          source .venv/bin/activate
          cd rust-src
          RUSTFLAGS="-C target-feature=+avx2" maturin develop --release --target x86_64-unknown-linux-gnu
          
      - name: Build Linux executable
        run: |
          source .venv/bin/activate
          pyinstaller linux-x86.spec
          
      - name: Create distribution package
        run: |
          source .venv/bin/activate
          cd dist/linux-x86
          VERSION=$(python -c "from importlib.metadata import version; print(version('vfmc'))")
          tar -czvf VFMC-v$VERSION-Linux.tar.gz VFMC
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VFMC-Linux
          path: dist/linux-x86/*.tar.gz
          
      - name: Check for GitHub Release
        id: check_release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "Building from tag: $TAG"
          if gh release view $TAG &>/dev/null; then
            echo "release_exists=true" >> $GITHUB_OUTPUT
            echo "tag=$TAG" >> $GITHUB_OUTPUT
          else
            echo "release_exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload to existing GitHub Release
        if: steps.check_release.outputs.release_exists == 'true'
        run: |
          TAG=${{ steps.check_release.outputs.tag }}
          for file in dist/linux-x86/*.tar.gz; do
            echo "Uploading $file to release $TAG"
            gh release upload $TAG "$file" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
