# .github/workflows/build-and-publish.yml
name: Publish vfmc_core

on:
  workflow_dispatch:
#  push:
#    tags:
#      - "v*"  # Trigger on version tags like v1.0.0

permissions:
  contents: read

jobs:
  build-linux-windows:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --out dist --find-interpreter
          sccache: 'true'
          working-directory: rust-src

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: dist

  build-macos:
    name: Build wheels on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Use a specific Python version

      - name: Build wheels for aarch64
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --out dist --target aarch64-apple-darwin --find-interpreter
          sccache: 'true'
          working-directory: rust-src

      - name: Build wheels for x86_64
        uses: PyO3/maturin-action@v1
        env:
          RUSTFLAGS: "-C target-feature=+avx2"
        with:
          command: build
          args: --release --out dist --target x86_64-apple-darwin --find-interpreter
          sccache: 'true'
          working-directory: rust-src

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: dist

  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        uses: PyO3/maturin-action@v1
        with:
          command: sdist
          args: --out dist
          working-directory: rust-src

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build-linux-windows, build-macos, build-sdist]
    steps:
      - uses: actions/download-artifact@v4

      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: upload
          args: --non-interactive --skip-existing wheels*/*